noun=input("Enter a noun: ")
verb=input("Enter a verb: ")
adj=input("Enter an adjective: ")
adv=input("Enter an adverb: ")
print("Do you {f_verb} your {f_adj} {f_noun} {f_adv}?".format(f_noun=noun,f_verb=verb,f_adj=adj,f_adv=adv))
